### ISSUE TITLE
The Plugin Shows Error

### ISSUE THREAD

**Issue by CBJaxxx** [Atten007/MCreator-Forge-1.19.4#1]
https://gyazo.com/a6783c51a844790d76e6c5a5ef4fab47

this is the error that popped up when I opened Mcreator with this plugin, i also have java plugins enabled.

**Comment by Atten007** [comment]
You need to unpack the ZIP file in the .mcreator/plugins directory. I can also upload a folder next time. I also had this error and could fix it by unpacking the ZIP file to the .mcreator/plugins directory and then deleting the zip file.

**Comment by CBJaxxx** [comment]
I will give this a shot a let you know if it works for me thank you.

**Comment by CBJaxxx** [comment]
> You need to unpack the ZIP file in the .mcreator/plugins directory. I can also upload a folder next time. I also had this error and could fix it by unpacking the ZIP file to the .mcreator/plugins directory and then deleting the zip file.

I upacked the ZIP and put the MCreator-Forge-1.19.4-main folder that was inside into the .mcreator/plugins directory, but the plugin didn't show up in the Mcreator plugins.

**Comment by Atten007** [comment]
Do you have deleted the zip file?

**Comment by CBJaxxx** [comment]
yes

**Comment by CBJaxxx** [comment]
I will send pictures of what the folder looks like inside the plugins folder

**Comment by Atten007** [comment]
Ok, do you have restarted MCreator?

**Comment by CBJaxxx** [comment]
https://gyazo.com/51ee83b9169823ef8399a8adf32e9eb7
https://gyazo.com/aa01b8431e01920c38b0e5ca4e312491
this is what the files look like inside my Mcreator plugins directory.

**Comment by CBJaxxx** [comment]
yes I restart Mcreator every time

**Comment by Atten007** [comment]
Hmm... that's weird. The plugin is working on my MCreator, but not on yours. I'll respond later because I'm going to eat breakfast now.

**Comment by CBJaxxx** [comment]
no worries, please upload a fix or let me know if you find one later. thanks

**Comment by Atten007** [comment]
Fixed?

**Comment by CBJaxxx** [comment]
I downloaded the latest version you uploaded but I still get this error.
https://gyazo.com/820997856efcbf201e8f358b706aa26e
This is what my file looks like.
https://gyazo.com/f32dc3a8e49363f8fa11e69b77b5ff81

**Comment by Atten007** [comment]
Or you can activate auto-unzipping if your OS supports it and then put in the folder into your .mcreator/plugins folder.

**Comment by CBJaxxx** [comment]
usually Mcreator plugins work even when they are zipped. I am using windows but it really doubt that would be the issue since its the same build of Mcreator.

**Comment by CBJaxxx** [comment]
I compared this Generator to another one and it seems that the only other file they have is the plugin.json file but I cant seem to find that in your Generator, is it missing?

**Comment by CBJaxxx** [comment]
https://gyazo.com/fb945bb958f8a6fbf9e3ab1add513be7
This link shows a picture of the plugin.json file of the other Generator plugin and your plugin on the right is missing it. I am pretty certain since that file is gone that the plugin wont work.

**Comment by Atten007** [comment]
Hello, I just published a new release of the Generator. You need to unpack the ZIP file and then delete the zip file and move the folder into "C:/Users/YOURNAME/.mcreator/plugins.
